/**
 * @file figma-property-registry.ts
 * @description Single source of truth for Figma property discovery + metadata.
 *
 * Three sections:
 *   1. PROPERTY_REGISTRY (auto-generated) — per-node-type property lists
 *   2. BLACKLIST (hand-maintained) — properties to exclude from serialization
 *   3. PROPERTY_META (hand-maintained) — enrichment: defaults, enums, constraints
 *      Replaces the old PROP_METADATA from figma-api.ts
 *
 * Re-generate section 1: npx tsx tools/extract-figma-props.ts
 */

export interface PropertyDef {
  key: string;
  valueType: 'number' | 'string' | 'boolean' | 'enum' | 'object' | 'array';
  readonly: boolean;
}

// ═══════════════════════════════════════════════════════════════
// Section 1: Per-node-type property lists (auto-generated)
// ═══════════════════════════════════════════════════════════════

export const PROPERTY_REGISTRY: Record<string, PropertyDef[]> = {
  FRAME: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'detachedInfo', valueType: 'object', readonly: true },
    { key: 'layoutGrids', valueType: 'array', readonly: false },
    { key: 'gridStyleId', valueType: 'string', readonly: false },
    { key: 'clipsContent', valueType: 'boolean', readonly: false },
    { key: 'guides', valueType: 'array', readonly: false },
    { key: 'inferredAutoLayout', valueType: 'object', readonly: false },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'children', valueType: 'array', readonly: true },
    { key: 'expanded', valueType: 'boolean', readonly: false },
    { key: 'backgrounds', valueType: 'array', readonly: false },
    { key: 'backgroundStyleId', valueType: 'string', readonly: false },
    { key: 'strokeCap', valueType: 'object', readonly: false },
    { key: 'strokeMiterLimit', valueType: 'number', readonly: false },
    { key: 'fillGeometry', valueType: 'object', readonly: true },
    { key: 'strokes', valueType: 'array', readonly: false },
    { key: 'strokeStyleId', valueType: 'string', readonly: false },
    { key: 'strokeWeight', valueType: 'object', readonly: false },
    { key: 'strokeJoin', valueType: 'object', readonly: false },
    { key: 'strokeAlign', valueType: 'object', readonly: false },
    { key: 'dashPattern', valueType: 'array', readonly: false },
    { key: 'strokeGeometry', valueType: 'object', readonly: true },
    { key: 'fills', valueType: 'object', readonly: false },
    { key: 'fillStyleId', valueType: 'object', readonly: false },
    { key: 'cornerRadius', valueType: 'object', readonly: false },
    { key: 'cornerSmoothing', valueType: 'number', readonly: false },
    { key: 'topLeftRadius', valueType: 'number', readonly: false },
    { key: 'topRightRadius', valueType: 'number', readonly: false },
    { key: 'bottomLeftRadius', valueType: 'number', readonly: false },
    { key: 'bottomRightRadius', valueType: 'number', readonly: false },
    { key: 'isMask', valueType: 'boolean', readonly: false },
    { key: 'maskType', valueType: 'object', readonly: false },
    { key: 'effects', valueType: 'array', readonly: false },
    { key: 'effectStyleId', valueType: 'string', readonly: false },
    { key: 'opacity', valueType: 'number', readonly: false },
    { key: 'blendMode', valueType: 'object', readonly: false },
    { key: 'constraints', valueType: 'object', readonly: false },
    { key: 'absoluteRenderBounds', valueType: 'object', readonly: true },
    { key: 'constrainProportions', valueType: 'boolean', readonly: false },
    { key: 'rotation', valueType: 'number', readonly: false },
    { key: 'layoutSizingHorizontal', valueType: 'object', readonly: false },
    { key: 'layoutSizingVertical', valueType: 'object', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'layoutAlign', valueType: 'object', readonly: false },
    { key: 'layoutGrow', valueType: 'number', readonly: false },
    { key: 'layoutPositioning', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'strokeTopWeight', valueType: 'number', readonly: false },
    { key: 'strokeBottomWeight', valueType: 'number', readonly: false },
    { key: 'strokeLeftWeight', valueType: 'number', readonly: false },
    { key: 'strokeRightWeight', valueType: 'number', readonly: false },
    { key: 'layoutMode', valueType: 'object', readonly: false },
    { key: 'layoutWrap', valueType: 'object', readonly: false },
    { key: 'paddingLeft', valueType: 'number', readonly: false },
    { key: 'paddingRight', valueType: 'number', readonly: false },
    { key: 'paddingTop', valueType: 'number', readonly: false },
    { key: 'paddingBottom', valueType: 'number', readonly: false },
    { key: 'horizontalPadding', valueType: 'number', readonly: false },
    { key: 'verticalPadding', valueType: 'number', readonly: false },
    { key: 'primaryAxisSizingMode', valueType: 'object', readonly: false },
    { key: 'counterAxisSizingMode', valueType: 'object', readonly: false },
    { key: 'primaryAxisAlignItems', valueType: 'object', readonly: false },
    { key: 'counterAxisAlignItems', valueType: 'object', readonly: false },
    { key: 'counterAxisAlignContent', valueType: 'object', readonly: false },
    { key: 'itemSpacing', valueType: 'number', readonly: false },
    { key: 'counterAxisSpacing', valueType: 'number', readonly: false },
    { key: 'itemReverseZIndex', valueType: 'boolean', readonly: false },
    { key: 'strokesIncludedInLayout', valueType: 'boolean', readonly: false },
    { key: 'targetAspectRatio', valueType: 'object', readonly: true },
    { key: 'annotations', valueType: 'array', readonly: false },
    { key: 'devStatus', valueType: 'object', readonly: false },
    { key: 'overflowDirection', valueType: 'object', readonly: false },
    { key: 'numberOfFixedChildren', valueType: 'number', readonly: false },
    { key: 'overlayPositionType', valueType: 'object', readonly: true },
    { key: 'overlayBackground', valueType: 'object', readonly: true },
    { key: 'overlayBackgroundInteraction', valueType: 'object', readonly: true },
    { key: 'reactions', valueType: 'array', readonly: false },
  ],
  TEXT: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'textAlignHorizontal', valueType: 'object', readonly: false },
    { key: 'textAlignVertical', valueType: 'object', readonly: false },
    { key: 'textAutoResize', valueType: 'object', readonly: false },
    { key: 'textTruncation', valueType: 'object', readonly: false },
    { key: 'maxLines', valueType: 'number', readonly: false },
    { key: 'autoRename', valueType: 'boolean', readonly: false },
    { key: 'textStyleId', valueType: 'object', readonly: false },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'reactions', valueType: 'array', readonly: false },
    { key: 'isMask', valueType: 'boolean', readonly: false },
    { key: 'maskType', valueType: 'object', readonly: false },
    { key: 'effects', valueType: 'array', readonly: false },
    { key: 'effectStyleId', valueType: 'string', readonly: false },
    { key: 'opacity', valueType: 'number', readonly: false },
    { key: 'blendMode', valueType: 'object', readonly: false },
    { key: 'strokeCap', valueType: 'object', readonly: false },
    { key: 'strokeMiterLimit', valueType: 'number', readonly: false },
    { key: 'fillGeometry', valueType: 'object', readonly: true },
    { key: 'strokes', valueType: 'array', readonly: false },
    { key: 'strokeStyleId', valueType: 'string', readonly: false },
    { key: 'strokeWeight', valueType: 'object', readonly: false },
    { key: 'strokeJoin', valueType: 'object', readonly: false },
    { key: 'strokeAlign', valueType: 'object', readonly: false },
    { key: 'dashPattern', valueType: 'array', readonly: false },
    { key: 'strokeGeometry', valueType: 'object', readonly: true },
    { key: 'fills', valueType: 'object', readonly: false },
    { key: 'fillStyleId', valueType: 'object', readonly: false },
    { key: 'absoluteRenderBounds', valueType: 'object', readonly: true },
    { key: 'constrainProportions', valueType: 'boolean', readonly: false },
    { key: 'rotation', valueType: 'number', readonly: false },
    { key: 'layoutSizingHorizontal', valueType: 'object', readonly: false },
    { key: 'layoutSizingVertical', valueType: 'object', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'layoutAlign', valueType: 'object', readonly: false },
    { key: 'layoutGrow', valueType: 'number', readonly: false },
    { key: 'layoutPositioning', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'constraints', valueType: 'object', readonly: false },
    { key: 'hasMissingFont', valueType: 'boolean', readonly: true },
    { key: 'paragraphIndent', valueType: 'number', readonly: false },
    { key: 'paragraphSpacing', valueType: 'number', readonly: false },
    { key: 'listSpacing', valueType: 'number', readonly: false },
    { key: 'hangingPunctuation', valueType: 'boolean', readonly: false },
    { key: 'hangingList', valueType: 'boolean', readonly: false },
    { key: 'fontSize', valueType: 'object', readonly: false },
    { key: 'fontName', valueType: 'object', readonly: false },
    { key: 'fontWeight', valueType: 'object', readonly: true },
    { key: 'textCase', valueType: 'object', readonly: false },
    { key: 'openTypeFeatures', valueType: 'object', readonly: true },
    { key: 'textDecoration', valueType: 'object', readonly: false },
    { key: 'textDecorationStyle', valueType: 'object', readonly: false },
    { key: 'textDecorationOffset', valueType: 'object', readonly: false },
    { key: 'textDecorationThickness', valueType: 'object', readonly: false },
    { key: 'textDecorationColor', valueType: 'object', readonly: false },
    { key: 'textDecorationSkipInk', valueType: 'object', readonly: false },
    { key: 'letterSpacing', valueType: 'object', readonly: false },
    { key: 'lineHeight', valueType: 'object', readonly: false },
    { key: 'leadingTrim', valueType: 'object', readonly: false },
    { key: 'hyperlink', valueType: 'object', readonly: false },
    { key: 'characters', valueType: 'string', readonly: false },
    { key: 'annotations', valueType: 'array', readonly: false },
    { key: 'targetAspectRatio', valueType: 'object', readonly: true },
  ],
  RECTANGLE: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'reactions', valueType: 'array', readonly: false },
    { key: 'isMask', valueType: 'boolean', readonly: false },
    { key: 'maskType', valueType: 'object', readonly: false },
    { key: 'effects', valueType: 'array', readonly: false },
    { key: 'effectStyleId', valueType: 'string', readonly: false },
    { key: 'opacity', valueType: 'number', readonly: false },
    { key: 'blendMode', valueType: 'object', readonly: false },
    { key: 'strokeCap', valueType: 'object', readonly: false },
    { key: 'strokeMiterLimit', valueType: 'number', readonly: false },
    { key: 'fillGeometry', valueType: 'object', readonly: true },
    { key: 'strokes', valueType: 'array', readonly: false },
    { key: 'strokeStyleId', valueType: 'string', readonly: false },
    { key: 'strokeWeight', valueType: 'object', readonly: false },
    { key: 'strokeJoin', valueType: 'object', readonly: false },
    { key: 'strokeAlign', valueType: 'object', readonly: false },
    { key: 'dashPattern', valueType: 'array', readonly: false },
    { key: 'strokeGeometry', valueType: 'object', readonly: true },
    { key: 'fills', valueType: 'object', readonly: false },
    { key: 'fillStyleId', valueType: 'object', readonly: false },
    { key: 'absoluteRenderBounds', valueType: 'object', readonly: true },
    { key: 'constrainProportions', valueType: 'boolean', readonly: false },
    { key: 'rotation', valueType: 'number', readonly: false },
    { key: 'layoutSizingHorizontal', valueType: 'object', readonly: false },
    { key: 'layoutSizingVertical', valueType: 'object', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'layoutAlign', valueType: 'object', readonly: false },
    { key: 'layoutGrow', valueType: 'number', readonly: false },
    { key: 'layoutPositioning', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'constraints', valueType: 'object', readonly: false },
    { key: 'cornerRadius', valueType: 'object', readonly: false },
    { key: 'cornerSmoothing', valueType: 'number', readonly: false },
    { key: 'topLeftRadius', valueType: 'number', readonly: false },
    { key: 'topRightRadius', valueType: 'number', readonly: false },
    { key: 'bottomLeftRadius', valueType: 'number', readonly: false },
    { key: 'bottomRightRadius', valueType: 'number', readonly: false },
    { key: 'strokeTopWeight', valueType: 'number', readonly: false },
    { key: 'strokeBottomWeight', valueType: 'number', readonly: false },
    { key: 'strokeLeftWeight', valueType: 'number', readonly: false },
    { key: 'strokeRightWeight', valueType: 'number', readonly: false },
    { key: 'annotations', valueType: 'array', readonly: false },
    { key: 'targetAspectRatio', valueType: 'object', readonly: true },
  ],
  ELLIPSE: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'arcData', valueType: 'object', readonly: false },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'reactions', valueType: 'array', readonly: false },
    { key: 'isMask', valueType: 'boolean', readonly: false },
    { key: 'maskType', valueType: 'object', readonly: false },
    { key: 'effects', valueType: 'array', readonly: false },
    { key: 'effectStyleId', valueType: 'string', readonly: false },
    { key: 'opacity', valueType: 'number', readonly: false },
    { key: 'blendMode', valueType: 'object', readonly: false },
    { key: 'strokeCap', valueType: 'object', readonly: false },
    { key: 'strokeMiterLimit', valueType: 'number', readonly: false },
    { key: 'fillGeometry', valueType: 'object', readonly: true },
    { key: 'strokes', valueType: 'array', readonly: false },
    { key: 'strokeStyleId', valueType: 'string', readonly: false },
    { key: 'strokeWeight', valueType: 'object', readonly: false },
    { key: 'strokeJoin', valueType: 'object', readonly: false },
    { key: 'strokeAlign', valueType: 'object', readonly: false },
    { key: 'dashPattern', valueType: 'array', readonly: false },
    { key: 'strokeGeometry', valueType: 'object', readonly: true },
    { key: 'fills', valueType: 'object', readonly: false },
    { key: 'fillStyleId', valueType: 'object', readonly: false },
    { key: 'absoluteRenderBounds', valueType: 'object', readonly: true },
    { key: 'constrainProportions', valueType: 'boolean', readonly: false },
    { key: 'rotation', valueType: 'number', readonly: false },
    { key: 'layoutSizingHorizontal', valueType: 'object', readonly: false },
    { key: 'layoutSizingVertical', valueType: 'object', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'layoutAlign', valueType: 'object', readonly: false },
    { key: 'layoutGrow', valueType: 'number', readonly: false },
    { key: 'layoutPositioning', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'constraints', valueType: 'object', readonly: false },
    { key: 'cornerRadius', valueType: 'object', readonly: false },
    { key: 'cornerSmoothing', valueType: 'number', readonly: false },
    { key: 'annotations', valueType: 'array', readonly: false },
    { key: 'targetAspectRatio', valueType: 'object', readonly: true },
  ],
  LINE: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'reactions', valueType: 'array', readonly: false },
    { key: 'isMask', valueType: 'boolean', readonly: false },
    { key: 'maskType', valueType: 'object', readonly: false },
    { key: 'effects', valueType: 'array', readonly: false },
    { key: 'effectStyleId', valueType: 'string', readonly: false },
    { key: 'opacity', valueType: 'number', readonly: false },
    { key: 'blendMode', valueType: 'object', readonly: false },
    { key: 'strokeCap', valueType: 'object', readonly: false },
    { key: 'strokeMiterLimit', valueType: 'number', readonly: false },
    { key: 'fillGeometry', valueType: 'object', readonly: true },
    { key: 'strokes', valueType: 'array', readonly: false },
    { key: 'strokeStyleId', valueType: 'string', readonly: false },
    { key: 'strokeWeight', valueType: 'object', readonly: false },
    { key: 'strokeJoin', valueType: 'object', readonly: false },
    { key: 'strokeAlign', valueType: 'object', readonly: false },
    { key: 'dashPattern', valueType: 'array', readonly: false },
    { key: 'strokeGeometry', valueType: 'object', readonly: true },
    { key: 'fills', valueType: 'object', readonly: false },
    { key: 'fillStyleId', valueType: 'object', readonly: false },
    { key: 'absoluteRenderBounds', valueType: 'object', readonly: true },
    { key: 'constrainProportions', valueType: 'boolean', readonly: false },
    { key: 'rotation', valueType: 'number', readonly: false },
    { key: 'layoutSizingHorizontal', valueType: 'object', readonly: false },
    { key: 'layoutSizingVertical', valueType: 'object', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'layoutAlign', valueType: 'object', readonly: false },
    { key: 'layoutGrow', valueType: 'number', readonly: false },
    { key: 'layoutPositioning', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'constraints', valueType: 'object', readonly: false },
    { key: 'annotations', valueType: 'array', readonly: false },
  ],
  VECTOR: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'reactions', valueType: 'array', readonly: false },
    { key: 'isMask', valueType: 'boolean', readonly: false },
    { key: 'maskType', valueType: 'object', readonly: false },
    { key: 'effects', valueType: 'array', readonly: false },
    { key: 'effectStyleId', valueType: 'string', readonly: false },
    { key: 'opacity', valueType: 'number', readonly: false },
    { key: 'blendMode', valueType: 'object', readonly: false },
    { key: 'strokeCap', valueType: 'object', readonly: false },
    { key: 'strokeMiterLimit', valueType: 'number', readonly: false },
    { key: 'fillGeometry', valueType: 'object', readonly: true },
    { key: 'strokes', valueType: 'array', readonly: false },
    { key: 'strokeStyleId', valueType: 'string', readonly: false },
    { key: 'strokeWeight', valueType: 'object', readonly: false },
    { key: 'strokeJoin', valueType: 'object', readonly: false },
    { key: 'strokeAlign', valueType: 'object', readonly: false },
    { key: 'dashPattern', valueType: 'array', readonly: false },
    { key: 'strokeGeometry', valueType: 'object', readonly: true },
    { key: 'fills', valueType: 'object', readonly: false },
    { key: 'fillStyleId', valueType: 'object', readonly: false },
    { key: 'absoluteRenderBounds', valueType: 'object', readonly: true },
    { key: 'constrainProportions', valueType: 'boolean', readonly: false },
    { key: 'rotation', valueType: 'number', readonly: false },
    { key: 'layoutSizingHorizontal', valueType: 'object', readonly: false },
    { key: 'layoutSizingVertical', valueType: 'object', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'layoutAlign', valueType: 'object', readonly: false },
    { key: 'layoutGrow', valueType: 'number', readonly: false },
    { key: 'layoutPositioning', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'constraints', valueType: 'object', readonly: false },
    { key: 'cornerRadius', valueType: 'object', readonly: false },
    { key: 'cornerSmoothing', valueType: 'number', readonly: false },
    { key: 'vectorNetwork', valueType: 'object', readonly: false },
    { key: 'vectorPaths', valueType: 'object', readonly: false },
    { key: 'handleMirroring', valueType: 'object', readonly: false },
    { key: 'annotations', valueType: 'array', readonly: false },
    { key: 'targetAspectRatio', valueType: 'object', readonly: true },
  ],
  STAR: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'pointCount', valueType: 'number', readonly: false },
    { key: 'innerRadius', valueType: 'number', readonly: false },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'reactions', valueType: 'array', readonly: false },
    { key: 'isMask', valueType: 'boolean', readonly: false },
    { key: 'maskType', valueType: 'object', readonly: false },
    { key: 'effects', valueType: 'array', readonly: false },
    { key: 'effectStyleId', valueType: 'string', readonly: false },
    { key: 'opacity', valueType: 'number', readonly: false },
    { key: 'blendMode', valueType: 'object', readonly: false },
    { key: 'strokeCap', valueType: 'object', readonly: false },
    { key: 'strokeMiterLimit', valueType: 'number', readonly: false },
    { key: 'fillGeometry', valueType: 'object', readonly: true },
    { key: 'strokes', valueType: 'array', readonly: false },
    { key: 'strokeStyleId', valueType: 'string', readonly: false },
    { key: 'strokeWeight', valueType: 'object', readonly: false },
    { key: 'strokeJoin', valueType: 'object', readonly: false },
    { key: 'strokeAlign', valueType: 'object', readonly: false },
    { key: 'dashPattern', valueType: 'array', readonly: false },
    { key: 'strokeGeometry', valueType: 'object', readonly: true },
    { key: 'fills', valueType: 'object', readonly: false },
    { key: 'fillStyleId', valueType: 'object', readonly: false },
    { key: 'absoluteRenderBounds', valueType: 'object', readonly: true },
    { key: 'constrainProportions', valueType: 'boolean', readonly: false },
    { key: 'rotation', valueType: 'number', readonly: false },
    { key: 'layoutSizingHorizontal', valueType: 'object', readonly: false },
    { key: 'layoutSizingVertical', valueType: 'object', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'layoutAlign', valueType: 'object', readonly: false },
    { key: 'layoutGrow', valueType: 'number', readonly: false },
    { key: 'layoutPositioning', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'constraints', valueType: 'object', readonly: false },
    { key: 'cornerRadius', valueType: 'object', readonly: false },
    { key: 'cornerSmoothing', valueType: 'number', readonly: false },
    { key: 'annotations', valueType: 'array', readonly: false },
    { key: 'targetAspectRatio', valueType: 'object', readonly: true },
  ],
  POLYGON: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'pointCount', valueType: 'number', readonly: false },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'reactions', valueType: 'array', readonly: false },
    { key: 'isMask', valueType: 'boolean', readonly: false },
    { key: 'maskType', valueType: 'object', readonly: false },
    { key: 'effects', valueType: 'array', readonly: false },
    { key: 'effectStyleId', valueType: 'string', readonly: false },
    { key: 'opacity', valueType: 'number', readonly: false },
    { key: 'blendMode', valueType: 'object', readonly: false },
    { key: 'strokeCap', valueType: 'object', readonly: false },
    { key: 'strokeMiterLimit', valueType: 'number', readonly: false },
    { key: 'fillGeometry', valueType: 'object', readonly: true },
    { key: 'strokes', valueType: 'array', readonly: false },
    { key: 'strokeStyleId', valueType: 'string', readonly: false },
    { key: 'strokeWeight', valueType: 'object', readonly: false },
    { key: 'strokeJoin', valueType: 'object', readonly: false },
    { key: 'strokeAlign', valueType: 'object', readonly: false },
    { key: 'dashPattern', valueType: 'array', readonly: false },
    { key: 'strokeGeometry', valueType: 'object', readonly: true },
    { key: 'fills', valueType: 'object', readonly: false },
    { key: 'fillStyleId', valueType: 'object', readonly: false },
    { key: 'absoluteRenderBounds', valueType: 'object', readonly: true },
    { key: 'constrainProportions', valueType: 'boolean', readonly: false },
    { key: 'rotation', valueType: 'number', readonly: false },
    { key: 'layoutSizingHorizontal', valueType: 'object', readonly: false },
    { key: 'layoutSizingVertical', valueType: 'object', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'layoutAlign', valueType: 'object', readonly: false },
    { key: 'layoutGrow', valueType: 'number', readonly: false },
    { key: 'layoutPositioning', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'constraints', valueType: 'object', readonly: false },
    { key: 'cornerRadius', valueType: 'object', readonly: false },
    { key: 'cornerSmoothing', valueType: 'number', readonly: false },
    { key: 'annotations', valueType: 'array', readonly: false },
    { key: 'targetAspectRatio', valueType: 'object', readonly: true },
  ],
  COMPONENT: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'instances', valueType: 'array', readonly: true },
    { key: 'detachedInfo', valueType: 'object', readonly: true },
    { key: 'layoutGrids', valueType: 'array', readonly: false },
    { key: 'gridStyleId', valueType: 'string', readonly: false },
    { key: 'clipsContent', valueType: 'boolean', readonly: false },
    { key: 'guides', valueType: 'array', readonly: false },
    { key: 'inferredAutoLayout', valueType: 'object', readonly: false },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'children', valueType: 'array', readonly: true },
    { key: 'expanded', valueType: 'boolean', readonly: false },
    { key: 'backgrounds', valueType: 'array', readonly: false },
    { key: 'backgroundStyleId', valueType: 'string', readonly: false },
    { key: 'strokeCap', valueType: 'object', readonly: false },
    { key: 'strokeMiterLimit', valueType: 'number', readonly: false },
    { key: 'fillGeometry', valueType: 'object', readonly: true },
    { key: 'strokes', valueType: 'array', readonly: false },
    { key: 'strokeStyleId', valueType: 'string', readonly: false },
    { key: 'strokeWeight', valueType: 'object', readonly: false },
    { key: 'strokeJoin', valueType: 'object', readonly: false },
    { key: 'strokeAlign', valueType: 'object', readonly: false },
    { key: 'dashPattern', valueType: 'array', readonly: false },
    { key: 'strokeGeometry', valueType: 'object', readonly: true },
    { key: 'fills', valueType: 'object', readonly: false },
    { key: 'fillStyleId', valueType: 'object', readonly: false },
    { key: 'cornerRadius', valueType: 'object', readonly: false },
    { key: 'cornerSmoothing', valueType: 'number', readonly: false },
    { key: 'topLeftRadius', valueType: 'number', readonly: false },
    { key: 'topRightRadius', valueType: 'number', readonly: false },
    { key: 'bottomLeftRadius', valueType: 'number', readonly: false },
    { key: 'bottomRightRadius', valueType: 'number', readonly: false },
    { key: 'isMask', valueType: 'boolean', readonly: false },
    { key: 'maskType', valueType: 'object', readonly: false },
    { key: 'effects', valueType: 'array', readonly: false },
    { key: 'effectStyleId', valueType: 'string', readonly: false },
    { key: 'opacity', valueType: 'number', readonly: false },
    { key: 'blendMode', valueType: 'object', readonly: false },
    { key: 'constraints', valueType: 'object', readonly: false },
    { key: 'absoluteRenderBounds', valueType: 'object', readonly: true },
    { key: 'constrainProportions', valueType: 'boolean', readonly: false },
    { key: 'rotation', valueType: 'number', readonly: false },
    { key: 'layoutSizingHorizontal', valueType: 'object', readonly: false },
    { key: 'layoutSizingVertical', valueType: 'object', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'layoutAlign', valueType: 'object', readonly: false },
    { key: 'layoutGrow', valueType: 'number', readonly: false },
    { key: 'layoutPositioning', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'strokeTopWeight', valueType: 'number', readonly: false },
    { key: 'strokeBottomWeight', valueType: 'number', readonly: false },
    { key: 'strokeLeftWeight', valueType: 'number', readonly: false },
    { key: 'strokeRightWeight', valueType: 'number', readonly: false },
    { key: 'layoutMode', valueType: 'object', readonly: false },
    { key: 'layoutWrap', valueType: 'object', readonly: false },
    { key: 'paddingLeft', valueType: 'number', readonly: false },
    { key: 'paddingRight', valueType: 'number', readonly: false },
    { key: 'paddingTop', valueType: 'number', readonly: false },
    { key: 'paddingBottom', valueType: 'number', readonly: false },
    { key: 'horizontalPadding', valueType: 'number', readonly: false },
    { key: 'verticalPadding', valueType: 'number', readonly: false },
    { key: 'primaryAxisSizingMode', valueType: 'object', readonly: false },
    { key: 'counterAxisSizingMode', valueType: 'object', readonly: false },
    { key: 'primaryAxisAlignItems', valueType: 'object', readonly: false },
    { key: 'counterAxisAlignItems', valueType: 'object', readonly: false },
    { key: 'counterAxisAlignContent', valueType: 'object', readonly: false },
    { key: 'itemSpacing', valueType: 'number', readonly: false },
    { key: 'counterAxisSpacing', valueType: 'number', readonly: false },
    { key: 'itemReverseZIndex', valueType: 'boolean', readonly: false },
    { key: 'strokesIncludedInLayout', valueType: 'boolean', readonly: false },
    { key: 'targetAspectRatio', valueType: 'object', readonly: true },
    { key: 'annotations', valueType: 'array', readonly: false },
    { key: 'devStatus', valueType: 'object', readonly: false },
    { key: 'overflowDirection', valueType: 'object', readonly: false },
    { key: 'numberOfFixedChildren', valueType: 'number', readonly: false },
    { key: 'overlayPositionType', valueType: 'object', readonly: true },
    { key: 'overlayBackground', valueType: 'object', readonly: true },
    { key: 'overlayBackgroundInteraction', valueType: 'object', readonly: true },
    { key: 'reactions', valueType: 'array', readonly: false },
    { key: 'description', valueType: 'string', readonly: false },
    { key: 'descriptionMarkdown', valueType: 'string', readonly: false },
    { key: 'documentationLinks', valueType: 'array', readonly: false },
    { key: 'remote', valueType: 'boolean', readonly: true },
    { key: 'key', valueType: 'string', readonly: true },
    { key: 'variantProperties', valueType: 'object', readonly: true },
    { key: 'componentPropertyDefinitions', valueType: 'object', readonly: true },
  ],
  COMPONENT_SET: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'defaultVariant', valueType: 'object', readonly: true },
    { key: 'variantGroupProperties', valueType: 'object', readonly: true },
    { key: 'detachedInfo', valueType: 'object', readonly: true },
    { key: 'layoutGrids', valueType: 'array', readonly: false },
    { key: 'gridStyleId', valueType: 'string', readonly: false },
    { key: 'clipsContent', valueType: 'boolean', readonly: false },
    { key: 'guides', valueType: 'array', readonly: false },
    { key: 'inferredAutoLayout', valueType: 'object', readonly: false },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'children', valueType: 'array', readonly: true },
    { key: 'expanded', valueType: 'boolean', readonly: false },
    { key: 'backgrounds', valueType: 'array', readonly: false },
    { key: 'backgroundStyleId', valueType: 'string', readonly: false },
    { key: 'strokeCap', valueType: 'object', readonly: false },
    { key: 'strokeMiterLimit', valueType: 'number', readonly: false },
    { key: 'fillGeometry', valueType: 'object', readonly: true },
    { key: 'strokes', valueType: 'array', readonly: false },
    { key: 'strokeStyleId', valueType: 'string', readonly: false },
    { key: 'strokeWeight', valueType: 'object', readonly: false },
    { key: 'strokeJoin', valueType: 'object', readonly: false },
    { key: 'strokeAlign', valueType: 'object', readonly: false },
    { key: 'dashPattern', valueType: 'array', readonly: false },
    { key: 'strokeGeometry', valueType: 'object', readonly: true },
    { key: 'fills', valueType: 'object', readonly: false },
    { key: 'fillStyleId', valueType: 'object', readonly: false },
    { key: 'cornerRadius', valueType: 'object', readonly: false },
    { key: 'cornerSmoothing', valueType: 'number', readonly: false },
    { key: 'topLeftRadius', valueType: 'number', readonly: false },
    { key: 'topRightRadius', valueType: 'number', readonly: false },
    { key: 'bottomLeftRadius', valueType: 'number', readonly: false },
    { key: 'bottomRightRadius', valueType: 'number', readonly: false },
    { key: 'isMask', valueType: 'boolean', readonly: false },
    { key: 'maskType', valueType: 'object', readonly: false },
    { key: 'effects', valueType: 'array', readonly: false },
    { key: 'effectStyleId', valueType: 'string', readonly: false },
    { key: 'opacity', valueType: 'number', readonly: false },
    { key: 'blendMode', valueType: 'object', readonly: false },
    { key: 'constraints', valueType: 'object', readonly: false },
    { key: 'absoluteRenderBounds', valueType: 'object', readonly: true },
    { key: 'constrainProportions', valueType: 'boolean', readonly: false },
    { key: 'rotation', valueType: 'number', readonly: false },
    { key: 'layoutSizingHorizontal', valueType: 'object', readonly: false },
    { key: 'layoutSizingVertical', valueType: 'object', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'layoutAlign', valueType: 'object', readonly: false },
    { key: 'layoutGrow', valueType: 'number', readonly: false },
    { key: 'layoutPositioning', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'strokeTopWeight', valueType: 'number', readonly: false },
    { key: 'strokeBottomWeight', valueType: 'number', readonly: false },
    { key: 'strokeLeftWeight', valueType: 'number', readonly: false },
    { key: 'strokeRightWeight', valueType: 'number', readonly: false },
    { key: 'layoutMode', valueType: 'object', readonly: false },
    { key: 'layoutWrap', valueType: 'object', readonly: false },
    { key: 'paddingLeft', valueType: 'number', readonly: false },
    { key: 'paddingRight', valueType: 'number', readonly: false },
    { key: 'paddingTop', valueType: 'number', readonly: false },
    { key: 'paddingBottom', valueType: 'number', readonly: false },
    { key: 'horizontalPadding', valueType: 'number', readonly: false },
    { key: 'verticalPadding', valueType: 'number', readonly: false },
    { key: 'primaryAxisSizingMode', valueType: 'object', readonly: false },
    { key: 'counterAxisSizingMode', valueType: 'object', readonly: false },
    { key: 'primaryAxisAlignItems', valueType: 'object', readonly: false },
    { key: 'counterAxisAlignItems', valueType: 'object', readonly: false },
    { key: 'counterAxisAlignContent', valueType: 'object', readonly: false },
    { key: 'itemSpacing', valueType: 'number', readonly: false },
    { key: 'counterAxisSpacing', valueType: 'number', readonly: false },
    { key: 'itemReverseZIndex', valueType: 'boolean', readonly: false },
    { key: 'strokesIncludedInLayout', valueType: 'boolean', readonly: false },
    { key: 'targetAspectRatio', valueType: 'object', readonly: true },
    { key: 'annotations', valueType: 'array', readonly: false },
    { key: 'devStatus', valueType: 'object', readonly: false },
    { key: 'description', valueType: 'string', readonly: false },
    { key: 'descriptionMarkdown', valueType: 'string', readonly: false },
    { key: 'documentationLinks', valueType: 'array', readonly: false },
    { key: 'remote', valueType: 'boolean', readonly: true },
    { key: 'key', valueType: 'string', readonly: true },
    { key: 'componentPropertyDefinitions', valueType: 'object', readonly: true },
  ],
  INSTANCE: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'mainComponent', valueType: 'object', readonly: false },
    { key: 'componentProperties', valueType: 'object', readonly: true },
    { key: 'scaleFactor', valueType: 'number', readonly: false },
    { key: 'exposedInstances', valueType: 'array', readonly: true },
    { key: 'isExposedInstance', valueType: 'boolean', readonly: false },
    { key: 'overrides', valueType: 'array', readonly: true },
    { key: 'detachedInfo', valueType: 'object', readonly: true },
    { key: 'layoutGrids', valueType: 'array', readonly: false },
    { key: 'gridStyleId', valueType: 'string', readonly: false },
    { key: 'clipsContent', valueType: 'boolean', readonly: false },
    { key: 'guides', valueType: 'array', readonly: false },
    { key: 'inferredAutoLayout', valueType: 'object', readonly: false },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'children', valueType: 'array', readonly: true },
    { key: 'expanded', valueType: 'boolean', readonly: false },
    { key: 'backgrounds', valueType: 'array', readonly: false },
    { key: 'backgroundStyleId', valueType: 'string', readonly: false },
    { key: 'strokeCap', valueType: 'object', readonly: false },
    { key: 'strokeMiterLimit', valueType: 'number', readonly: false },
    { key: 'fillGeometry', valueType: 'object', readonly: true },
    { key: 'strokes', valueType: 'array', readonly: false },
    { key: 'strokeStyleId', valueType: 'string', readonly: false },
    { key: 'strokeWeight', valueType: 'object', readonly: false },
    { key: 'strokeJoin', valueType: 'object', readonly: false },
    { key: 'strokeAlign', valueType: 'object', readonly: false },
    { key: 'dashPattern', valueType: 'array', readonly: false },
    { key: 'strokeGeometry', valueType: 'object', readonly: true },
    { key: 'fills', valueType: 'object', readonly: false },
    { key: 'fillStyleId', valueType: 'object', readonly: false },
    { key: 'cornerRadius', valueType: 'object', readonly: false },
    { key: 'cornerSmoothing', valueType: 'number', readonly: false },
    { key: 'topLeftRadius', valueType: 'number', readonly: false },
    { key: 'topRightRadius', valueType: 'number', readonly: false },
    { key: 'bottomLeftRadius', valueType: 'number', readonly: false },
    { key: 'bottomRightRadius', valueType: 'number', readonly: false },
    { key: 'isMask', valueType: 'boolean', readonly: false },
    { key: 'maskType', valueType: 'object', readonly: false },
    { key: 'effects', valueType: 'array', readonly: false },
    { key: 'effectStyleId', valueType: 'string', readonly: false },
    { key: 'opacity', valueType: 'number', readonly: false },
    { key: 'blendMode', valueType: 'object', readonly: false },
    { key: 'constraints', valueType: 'object', readonly: false },
    { key: 'absoluteRenderBounds', valueType: 'object', readonly: true },
    { key: 'constrainProportions', valueType: 'boolean', readonly: false },
    { key: 'rotation', valueType: 'number', readonly: false },
    { key: 'layoutSizingHorizontal', valueType: 'object', readonly: false },
    { key: 'layoutSizingVertical', valueType: 'object', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'layoutAlign', valueType: 'object', readonly: false },
    { key: 'layoutGrow', valueType: 'number', readonly: false },
    { key: 'layoutPositioning', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'strokeTopWeight', valueType: 'number', readonly: false },
    { key: 'strokeBottomWeight', valueType: 'number', readonly: false },
    { key: 'strokeLeftWeight', valueType: 'number', readonly: false },
    { key: 'strokeRightWeight', valueType: 'number', readonly: false },
    { key: 'layoutMode', valueType: 'object', readonly: false },
    { key: 'layoutWrap', valueType: 'object', readonly: false },
    { key: 'paddingLeft', valueType: 'number', readonly: false },
    { key: 'paddingRight', valueType: 'number', readonly: false },
    { key: 'paddingTop', valueType: 'number', readonly: false },
    { key: 'paddingBottom', valueType: 'number', readonly: false },
    { key: 'horizontalPadding', valueType: 'number', readonly: false },
    { key: 'verticalPadding', valueType: 'number', readonly: false },
    { key: 'primaryAxisSizingMode', valueType: 'object', readonly: false },
    { key: 'counterAxisSizingMode', valueType: 'object', readonly: false },
    { key: 'primaryAxisAlignItems', valueType: 'object', readonly: false },
    { key: 'counterAxisAlignItems', valueType: 'object', readonly: false },
    { key: 'counterAxisAlignContent', valueType: 'object', readonly: false },
    { key: 'itemSpacing', valueType: 'number', readonly: false },
    { key: 'counterAxisSpacing', valueType: 'number', readonly: false },
    { key: 'itemReverseZIndex', valueType: 'boolean', readonly: false },
    { key: 'strokesIncludedInLayout', valueType: 'boolean', readonly: false },
    { key: 'targetAspectRatio', valueType: 'object', readonly: true },
    { key: 'annotations', valueType: 'array', readonly: false },
    { key: 'devStatus', valueType: 'object', readonly: false },
    { key: 'overflowDirection', valueType: 'object', readonly: false },
    { key: 'numberOfFixedChildren', valueType: 'number', readonly: false },
    { key: 'overlayPositionType', valueType: 'object', readonly: true },
    { key: 'overlayBackground', valueType: 'object', readonly: true },
    { key: 'overlayBackgroundInteraction', valueType: 'object', readonly: true },
    { key: 'reactions', valueType: 'array', readonly: false },
    { key: 'variantProperties', valueType: 'object', readonly: true },
  ],
  GROUP: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'reactions', valueType: 'array', readonly: false },
    { key: 'children', valueType: 'array', readonly: true },
    { key: 'expanded', valueType: 'boolean', readonly: false },
    { key: 'backgrounds', valueType: 'array', readonly: false },
    { key: 'backgroundStyleId', valueType: 'string', readonly: false },
    { key: 'isMask', valueType: 'boolean', readonly: false },
    { key: 'maskType', valueType: 'object', readonly: false },
    { key: 'effects', valueType: 'array', readonly: false },
    { key: 'effectStyleId', valueType: 'string', readonly: false },
    { key: 'opacity', valueType: 'number', readonly: false },
    { key: 'blendMode', valueType: 'object', readonly: false },
    { key: 'absoluteRenderBounds', valueType: 'object', readonly: true },
    { key: 'constrainProportions', valueType: 'boolean', readonly: false },
    { key: 'rotation', valueType: 'number', readonly: false },
    { key: 'layoutSizingHorizontal', valueType: 'object', readonly: false },
    { key: 'layoutSizingVertical', valueType: 'object', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'layoutAlign', valueType: 'object', readonly: false },
    { key: 'layoutGrow', valueType: 'number', readonly: false },
    { key: 'layoutPositioning', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'targetAspectRatio', valueType: 'object', readonly: true },
  ],
  SECTION: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'sectionContentsHidden', valueType: 'boolean', readonly: false },
    { key: 'children', valueType: 'array', readonly: true },
    { key: 'fills', valueType: 'object', readonly: false },
    { key: 'fillStyleId', valueType: 'object', readonly: false },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'devStatus', valueType: 'object', readonly: false },
    { key: 'targetAspectRatio', valueType: 'object', readonly: true },
  ],
  BOOLEAN_OPERATION: [
    { key: 'type', valueType: 'object', readonly: true },
    { key: 'booleanOperation', valueType: 'object', readonly: false },
    { key: 'id', valueType: 'string', readonly: true },
    { key: 'parent', valueType: 'object', readonly: true },
    { key: 'name', valueType: 'string', readonly: false },
    { key: 'removed', valueType: 'boolean', readonly: true },
    { key: 'isAsset', valueType: 'boolean', readonly: true },
    { key: 'visible', valueType: 'boolean', readonly: false },
    { key: 'locked', valueType: 'boolean', readonly: false },
    { key: 'stuckNodes', valueType: 'array', readonly: true },
    { key: 'attachedConnectors', valueType: 'array', readonly: true },
    { key: 'componentPropertyReferences', valueType: 'object', readonly: false },
    { key: 'boundVariables', valueType: 'object', readonly: true },
    { key: 'inferredVariables', valueType: 'object', readonly: true },
    { key: 'resolvedVariableModes', valueType: 'object', readonly: false },
    { key: 'explicitVariableModes', valueType: 'object', readonly: false },
    { key: 'reactions', valueType: 'array', readonly: false },
    { key: 'isMask', valueType: 'boolean', readonly: false },
    { key: 'maskType', valueType: 'object', readonly: false },
    { key: 'effects', valueType: 'array', readonly: false },
    { key: 'effectStyleId', valueType: 'string', readonly: false },
    { key: 'opacity', valueType: 'number', readonly: false },
    { key: 'blendMode', valueType: 'object', readonly: false },
    { key: 'strokeCap', valueType: 'object', readonly: false },
    { key: 'strokeMiterLimit', valueType: 'number', readonly: false },
    { key: 'fillGeometry', valueType: 'object', readonly: true },
    { key: 'strokes', valueType: 'array', readonly: false },
    { key: 'strokeStyleId', valueType: 'string', readonly: false },
    { key: 'strokeWeight', valueType: 'object', readonly: false },
    { key: 'strokeJoin', valueType: 'object', readonly: false },
    { key: 'strokeAlign', valueType: 'object', readonly: false },
    { key: 'dashPattern', valueType: 'array', readonly: false },
    { key: 'strokeGeometry', valueType: 'object', readonly: true },
    { key: 'fills', valueType: 'object', readonly: false },
    { key: 'fillStyleId', valueType: 'object', readonly: false },
    { key: 'absoluteRenderBounds', valueType: 'object', readonly: true },
    { key: 'constrainProportions', valueType: 'boolean', readonly: false },
    { key: 'rotation', valueType: 'number', readonly: false },
    { key: 'layoutSizingHorizontal', valueType: 'object', readonly: false },
    { key: 'layoutSizingVertical', valueType: 'object', readonly: false },
    { key: 'x', valueType: 'number', readonly: false },
    { key: 'y', valueType: 'number', readonly: false },
    { key: 'width', valueType: 'number', readonly: true },
    { key: 'height', valueType: 'number', readonly: true },
    { key: 'minWidth', valueType: 'number', readonly: false },
    { key: 'maxWidth', valueType: 'number', readonly: false },
    { key: 'minHeight', valueType: 'number', readonly: false },
    { key: 'maxHeight', valueType: 'number', readonly: false },
    { key: 'relativeTransform', valueType: 'object', readonly: false },
    { key: 'absoluteTransform', valueType: 'object', readonly: true },
    { key: 'absoluteBoundingBox', valueType: 'object', readonly: true },
    { key: 'layoutAlign', valueType: 'object', readonly: false },
    { key: 'layoutGrow', valueType: 'number', readonly: false },
    { key: 'layoutPositioning', valueType: 'object', readonly: false },
    { key: 'exportSettings', valueType: 'array', readonly: false },
    { key: 'children', valueType: 'array', readonly: true },
    { key: 'cornerRadius', valueType: 'object', readonly: false },
    { key: 'cornerSmoothing', valueType: 'number', readonly: false },
    { key: 'expanded', valueType: 'boolean', readonly: false },
    { key: 'targetAspectRatio', valueType: 'object', readonly: true },
  ],
};

// ── Blacklist: properties to never serialize ──
// Methods, readonly/computed values, deprecated, internal/irrelevant

export const BLACKLIST = new Set([
  // Identity & structural (handled separately by serializer)
  'id', 'type', 'name', 'parent', 'children', 'removed',

  // Readonly / computed values
  'absoluteRenderBounds', 'absoluteBoundingBox', 'absoluteTransform',
  'fillGeometry', 'strokeGeometry', 'vectorNetwork', 'vectorPaths',
  'inferredAutoLayout', 'detachedInfo', 'targetAspectRatio',
  'overlayPositionType', 'overlayBackground', 'overlayBackgroundInteraction',
  'exportSettings', 'isAsset', 'stuckNodes', 'attachedConnectors',
  'variantProperties', 'componentPropertyDefinitions', 'componentProperties',
  'mainComponent', 'defaultVariant', 'variantGroupProperties',
  'overrides', 'exposedInstances', 'isExposedInstance',
  'hasMissingFont', 'openTypeFeatures',
  'relativeTransform', 'key', 'remote', 'prototypeStartNode',

  // Deprecated
  'horizontalPadding', 'verticalPadding', 'backgrounds', 'backgroundStyleId',
  'primaryAxisSizingMode', 'counterAxisSizingMode',

  // Style IDs (separate concern)
  'fillStyleId', 'strokeStyleId', 'effectStyleId', 'gridStyleId', 'textStyleId',

  // Internal / not design-relevant
  'reactions', 'guides', 'expanded', 'locked',
  'layoutGrids', 'flowStartingPoints', 'annotations',
  'componentPropertyReferences', 'boundVariables', 'inferredVariables',
  'resolvedVariableModes', 'explicitVariableModes',
  'devStatus', 'description', 'descriptionMarkdown', 'documentationLinks',
  'numberOfFixedChildren', 'overflowDirection',
  'isMask', 'maskType', 'handleMirroring', 'strokeMiterLimit',
  'autoRename', 'scaleFactor',
  'sectionContentsHidden',
  'textDecorationStyle', 'textDecorationOffset', 'textDecorationThickness',
  'textDecorationColor', 'textDecorationSkipInk',
  'leadingTrim', 'hyperlink', 'listSpacing', 'hangingPunctuation', 'hangingList',
  'arcData', 'pointCount', 'innerRadius', 'booleanOperation',
]);

// ═══════════════════════════════════════════════════════════════
// Section 3: Property enrichment metadata (hand-maintained)
// Replaces PROP_METADATA from figma-api.ts — single source of truth
// for defaults, enum maps, constraints, and DSL aliases.
//
// Keyed by DSL name (what the LLM sees). figmaKey only needed when
// it differs from the DSL name (currently only gap → itemSpacing).
// ═══════════════════════════════════════════════════════════════

export interface SizingConstraint {
  readonly requiresAutoLayout: 'self' | 'parent';
  readonly fallback: string;
}

export interface PropMeta {
  readonly figmaKey?: string;   // Figma API name when ≠ DSL key (e.g. gap → itemSpacing)
  readonly type: 'scalar' | 'color' | 'enum' | 'object' | 'virtual' | 'array' | 'string';
  readonly enumMap?: Record<string, string>;
  readonly defaultValue?: any;
  readonly min?: number;
  readonly max?: number;
  readonly valueConstraints?: Record<string, SizingConstraint>;
}

export const PROPERTY_META: Record<string, PropMeta> = {
  // Core Identity
  name: { type: 'string' },
  visible: { type: 'scalar', defaultValue: true },
  opacity: { type: 'scalar', defaultValue: 1, min: 0, max: 1 },

  // Layout
  layoutMode: { type: 'enum', enumMap: { VERTICAL: 'VERTICAL', HORIZONTAL: 'HORIZONTAL', NONE: 'NONE' }, defaultValue: 'NONE' },
  layoutSizingHorizontal: {
    type: 'enum', enumMap: { FIXED: 'FIXED', FILL: 'FILL', HUG: 'HUG', AUTO: 'HUG', STRETCH: 'FILL' },
    defaultValue: 'FIXED',
    valueConstraints: { HUG: { requiresAutoLayout: 'self', fallback: 'FIXED' }, FILL: { requiresAutoLayout: 'parent', fallback: 'HUG' } },
  },
  layoutSizingVertical: {
    type: 'enum', enumMap: { FIXED: 'FIXED', FILL: 'FILL', HUG: 'HUG', AUTO: 'HUG', STRETCH: 'FILL' },
    defaultValue: 'FIXED',
    valueConstraints: { HUG: { requiresAutoLayout: 'self', fallback: 'FIXED' }, FILL: { requiresAutoLayout: 'parent', fallback: 'HUG' } },
  },
  primaryAxisAlignItems: { type: 'enum', enumMap: { MIN: 'MIN', CENTER: 'CENTER', MAX: 'MAX', SPACE_BETWEEN: 'SPACE_BETWEEN' }, defaultValue: 'MIN' },
  counterAxisAlignItems: { type: 'enum', enumMap: { MIN: 'MIN', CENTER: 'CENTER', MAX: 'MAX', BASELINE: 'BASELINE' }, defaultValue: 'MIN' },
  gap: { figmaKey: 'itemSpacing', type: 'scalar', defaultValue: 0, min: 0, max: 1000 },
  counterAxisSpacing: { type: 'scalar', defaultValue: 0, min: 0, max: 1000 },
  paddingTop: { type: 'scalar', defaultValue: 0, min: 0, max: 1000 },
  paddingRight: { type: 'scalar', defaultValue: 0, min: 0, max: 1000 },
  paddingBottom: { type: 'scalar', defaultValue: 0, min: 0, max: 1000 },
  paddingLeft: { type: 'scalar', defaultValue: 0, min: 0, max: 1000 },
  layoutGrow: { type: 'scalar', defaultValue: 0, min: 0, max: 1 },
  layoutAlign: { type: 'enum', enumMap: { MIN: 'MIN', CENTER: 'CENTER', MAX: 'MAX', STRETCH: 'STRETCH', INHERIT: 'INHERIT' }, defaultValue: 'INHERIT' },
  layoutPositioning: { type: 'enum', enumMap: { AUTO: 'AUTO', RELATIVE: 'AUTO', ABSOLUTE: 'ABSOLUTE' }, defaultValue: 'AUTO' },
  constraints: { type: 'object', defaultValue: { horizontal: 'MIN', vertical: 'MIN' } },
  x: { type: 'scalar', defaultValue: 0 },
  y: { type: 'scalar', defaultValue: 0 },
  width: { type: 'scalar', min: 0.01, max: 10000 },
  height: { type: 'scalar', min: 0.01, max: 10000 },

  // Styling
  fills: { type: 'color', defaultValue: [] },
  strokes: { type: 'color', defaultValue: [] },
  strokeWeight: { type: 'scalar', defaultValue: 0, min: 0, max: 100 },
  cornerRadius: { type: 'scalar', defaultValue: 0, min: 0, max: 1000 },
  topLeftRadius: { type: 'scalar', min: 0, max: 1000 },
  topRightRadius: { type: 'scalar', min: 0, max: 1000 },
  bottomLeftRadius: { type: 'scalar', min: 0, max: 1000 },
  bottomRightRadius: { type: 'scalar', min: 0, max: 1000 },
  effects: { type: 'array', defaultValue: [] },

  // Text
  characters: { type: 'string' },
  fontSize: { type: 'scalar', min: 1, max: 1000 },
  fontWeight: { type: 'virtual' },
  fontFamily: { type: 'virtual' },
  textAlignHorizontal: { type: 'enum', enumMap: { LEFT: 'LEFT', CENTER: 'CENTER', RIGHT: 'RIGHT', JUSTIFIED: 'JUSTIFIED' } },
  textAlignVertical: { type: 'enum', enumMap: { TOP: 'TOP', CENTER: 'CENTER', BOTTOM: 'BOTTOM' } },
  textAutoResize: { type: 'enum', enumMap: { NONE: 'NONE', WIDTH_AND_HEIGHT: 'WIDTH_AND_HEIGHT', HEIGHT: 'HEIGHT', TRUNCATE: 'TRUNCATE' } },
  lineHeight: { type: 'scalar', min: 0, max: 1000 },
  letterSpacing: { type: 'scalar', min: -100, max: 1000 },
  textCase: { type: 'enum', enumMap: { ORIGINAL: 'ORIGINAL', UPPER: 'UPPER', LOWER: 'LOWER', TITLE: 'TITLE', SMALL_CAPS: 'SMALL_CAPS', SMALL_CAPS_FORCED: 'SMALL_CAPS_FORCED' } },
  textDecoration: { type: 'enum', enumMap: { NONE: 'NONE', UNDERLINE: 'UNDERLINE', STRIKETHROUGH: 'STRIKETHROUGH' } },
  textTruncation: { type: 'enum', enumMap: { DISABLED: 'DISABLED', ENDING: 'ENDING' }, defaultValue: 'DISABLED' },
  maxLines: { type: 'scalar', min: 1, max: 1000 },
  paragraphSpacing: { type: 'scalar', min: 0, max: 1000 },
  paragraphIndent: { type: 'scalar', min: 0, max: 1000 },

  // Misc
  rotation: { type: 'scalar', defaultValue: 0, min: -360, max: 360 },
  strokeAlign: { type: 'enum', enumMap: { INSIDE: 'INSIDE', OUTSIDE: 'OUTSIDE', CENTER: 'CENTER' }, defaultValue: 'INSIDE' },
  strokeJoin: { type: 'enum', enumMap: { MITER: 'MITER', BEVEL: 'BEVEL', ROUND: 'ROUND' }, defaultValue: 'MITER' },
  strokeCap: { type: 'enum', enumMap: { NONE: 'NONE', ROUND: 'ROUND', SQUARE: 'SQUARE', ARROW_LINES: 'ARROW_LINES', ARROW_EQUILATERAL: 'ARROW_EQUILATERAL' }, defaultValue: 'NONE' },
  dashPattern: { type: 'array', defaultValue: [] },
  strokeTopWeight: { type: 'scalar', min: 0, max: 100 },
  strokeRightWeight: { type: 'scalar', min: 0, max: 100 },
  strokeBottomWeight: { type: 'scalar', min: 0, max: 100 },
  strokeLeftWeight: { type: 'scalar', min: 0, max: 100 },
  blendMode: { type: 'enum', enumMap: {
    PASS_THROUGH: 'PASS_THROUGH', NORMAL: 'NORMAL', DARKEN: 'DARKEN', MULTIPLY: 'MULTIPLY',
    LINEAR_BURN: 'LINEAR_BURN', COLOR_BURN: 'COLOR_BURN', LIGHTEN: 'LIGHTEN', SCREEN: 'SCREEN',
    LINEAR_DODGE: 'LINEAR_DODGE', COLOR_DODGE: 'COLOR_DODGE', OVERLAY: 'OVERLAY',
    SOFT_LIGHT: 'SOFT_LIGHT', HARD_LIGHT: 'HARD_LIGHT', DIFFERENCE: 'DIFFERENCE',
    EXCLUSION: 'EXCLUSION', HUE: 'HUE', SATURATION: 'SATURATION', COLOR: 'COLOR', LUMINOSITY: 'LUMINOSITY',
  }, defaultValue: 'PASS_THROUGH' },
  cornerSmoothing: { type: 'scalar', defaultValue: 0, min: 0, max: 1 },
  clipsContent: { type: 'enum', enumMap: { 'true': 'true', 'false': 'false' }, defaultValue: false },
  layoutWrap: { type: 'enum', enumMap: { WRAP: 'WRAP', NO_WRAP: 'NO_WRAP' }, defaultValue: 'NO_WRAP' },
  strokesIncludedInLayout: { type: 'scalar', defaultValue: false },
  itemReverseZIndex: { type: 'scalar', defaultValue: false },
  minWidth: { type: 'scalar', min: 0, max: 10000 },
  maxWidth: { type: 'scalar', min: 0, max: 10000 },
  minHeight: { type: 'scalar', min: 0, max: 10000 },
  maxHeight: { type: 'scalar', min: 0, max: 10000 },
  constrainProportions: { type: 'scalar', defaultValue: false },

  // Virtual (not on Figma nodes, resolved at write time)
  semantic: { type: 'virtual' },
  variant: { type: 'virtual' },
  iconName: { type: 'virtual' },
};

// ── Derived lookups ──

/** Reverse map: Figma API name → DSL name (only for mismatched keys). */
export const FIGMA_TO_DSL: Record<string, string> = {};
for (const [dslKey, meta] of Object.entries(PROPERTY_META)) {
  if (meta.figmaKey) FIGMA_TO_DSL[meta.figmaKey] = dslKey;
}

/** Get all accepted input keys for an enum property. */
export function getEnumInputs(prop: string): string[] {
  const meta = PROPERTY_META[prop];
  if (!meta?.enumMap) return [];
  return Object.keys(meta.enumMap);
}

/** Get unique canonical output values for an enum property. */
export function getCanonicalValues(prop: string): string[] {
  const meta = PROPERTY_META[prop];
  if (!meta?.enumMap) return [];
  return [...new Set(Object.values(meta.enumMap))];
}

