/**
 * @file designPolicy.ts
 * @description Centralized design rules and recognition patterns.
 * 
 * Single Source of Truth for:
 * - Auto-name detection (to identify low-quality layers)
 * - Semantic keywords (to identify high-quality layers)
 * - Design standards (standard spacing, radii)
 */

// intent-keywords.json import removed

/** patterns for layers that are likely non-semantic/auto-generated by Figma */
export const AUTO_NAME_PATTERNS = [
    /^Frame\s*\d+$/i,
    /^Group\s*\d+$/i,
    /^Rectangle\s*\d+$/i,
    /^Ellipse\s*\d+$/i,
    /^Vector\s*\d+$/i,
    /^Line\s*\d+$/i,
    /^Polygon\s*\d+$/i,
    /^Star\s*\d+$/i,
    /^Text\s*\d+$/i,
    /^Image\s*\d+$/i,
    /^Component\s*\d+$/i,
];

// [DEPRECATED] Standard semantic keywords used for simple intent detection.
// Use DesignSystemConfig.patterns for dynamic keyword access.
export const SEMANTIC_KEYWORDS: string[] = [];

/** 
 * Patterns for identifying specific UI components in post-processing 
 */
export const COMPONENT_IDENTIFIERS = {
    SYSTEMS: {
        MATERIAL: /material design|material 3|md3|android style/i,
        IOS: /ios style|ios design|apple hig|apple design/i,
        SHADCN: /shadcn|tailwind|radix ui/i
    }
};
